# Copyright (c) 2025  Luke T. Shumaker
# SPDX-License-Identifier: BSD-3-Clause

name: Quality Assurance

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # The default GCC 13 has some false-positive warnings on our code.
      CC: gcc-14

    steps:
    - name: Install dev tools
      run: sudo apt install -y valgrind mypy black isort

    - name: Checkout repo
      uses: actions/checkout@v4

    - run: make

    - run: make lint

    - run: make check
